### ISSUE TITLE
Not working with latest JebBrains updates

### ISSUE THREAD

**Issue by it-sha** [mabdurrahman/custom-title-plugin#5]
For example for WebStorm 2019.3
Got an error 
`Plugin Error: Plugin "Custom Title" version was marked as incompatible.`

**Comment by psi-4ward** [comment]
Since theres no Title-Prefix like "WebStorm" this becomes more important

**Comment by n-shuvaev** [comment]
As a workaround i changed source code of another plugin https://plugins.jetbrains.com/plugin/7750-simple-titles, build jar file and enable it in Plugins.
Changed file: https://gist.github.com/n-shuvaev/ce4e6f3108c03b9e7b42f54c7f5be90d.
Now title include parent folder for solution and opened file name.

**Comment by allanlaal** [comment]
Plugin 'com.mabdurrahman.intellij.customtitle' failed to initialize and will be disabled. Please restart IntelliJ IDEA.

java.lang.ClassCastException: class com.intellij.openapi.application.impl.ApplicationImpl cannot be cast to class org.picocontainer.MutablePicoContainer (com.intellij.openapi.application.impl.ApplicationImpl and org.picocontainer.MutablePicoContainer are in unnamed module of loader com.intellij.util.lang.PathClassLoader @6aceb1a5)
    at com.mabdurrahman.intellij.customtitle.TitleComponent.initComponent(TitleComponent.java:24)
    at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:44)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
    at com.intellij.serviceContainer.ComponentManagerImpl$createInitOldComponentsTask$1.run(ComponentManagerImpl.kt:394)
    at com.intellij.idea.ApplicationLoader$prepareStart$1.run(ApplicationLoader.kt:208)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
    at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
    at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
    at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
    at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
    at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
    at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
    at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:393)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
